pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                bat 'cd networkmanager && mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
        	steps {
 			    bat 'cd networkmanager && mvn test'
            }
            post{
                always{
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
    }
}